# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'
strategy:
  matrix:
    Python36:
      python.version: '3.6'
      nox.env: 'tests-3.6'
    Python37:
      python.version: '3.7'
      nox.env: 'tests-3.7'
    Python38:
      python.version: '3.8'
      nox.env: 'tests-3.8'
    Linting:
      python.version: '3.7'
      nox.env: 'flake8'
    mypy:
      python.version: '3.7'
      nox.env: 'mypy'
    docs:
      python.version: '3.7'
      nox.env: 'docs'

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
    displayName: 'Use Python $(python.version)'

  - script: |
      python -m pip install --upgrade pip nox
    displayName: 'Install dependencies'

  - script: |
      nox --session $(nox.env)
    displayName: 'nox: $(nox.env)'


