# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: changelogd-ci

on:
  push:
    branches:
      - master
  
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ${{ matrix.platform }}
    strategy:
      max-parallel: 4
      matrix:
        platform: [ ubuntu-latest, macos-latest, windows-latest ]
        python-version: [ 3.6, 3.7, 3.8, 3.9, '3.10', '3.11' ]
    
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3.6
        if: matrix.platform == 'ubuntu-latest' && matrix.python-version == '3.6'
        run: |
          sudo add-apt-repository ppa:deadsnakes/ppa
          sudo apt-get update
          sudo apt-get install python3.6
      - name: Setup Nox
        if: matrix.platform != 'ubuntu-latest' || matrix.python-version != '3.6'
        uses: wntrblm/nox@2023.04.22
        with:
          python-versions: ${{ matrix.python-version }}
      - name: Run tests
        if: matrix.python-version != '3.6'
        run: |
          nox -s tests-${{ matrix.python-version }}
        env:
          PLATFORM: ${{ matrix.platform }}
      - name: Run tests ubuntu 3.6
        if: matrix.platform == 'ubuntu-latest' && matrix.python-version == '3.6'
        run: |
          sudo apt-get install -y nox
          nox -s tests-${{ matrix.python-version }}
        env:
          PLATFORM: ${{ matrix.platform }}
      - name: Update coverage
        uses: codecov/codecov-action@v1
  
  mypy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Setup Nox
        uses: aklajnert/setup-nox@v2.0.1
      - name: Run mypy
        run: |
          nox -s mypy
  flake8:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Setup Nox
        uses: aklajnert/setup-nox@v2.0.1
      - name: Run flake8
        run: |
          nox -s flake8
  check-docs:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Setup Nox
        uses: aklajnert/setup-nox@v2.0.1
      - name: Build docs
        run: |
          nox -s docs
